export type ServerEventRaw = Record<string, unknown> & {
  id?: string | number;
  _id?: string | number;
  name?: string;
  date?: string;
  status?: string;
  venue?: string;
  duration?: string;
  icon?: string;
  audiences?: unknown;
  audience_notes?: string | null;
  fine_amount?: number | string | null;
  fineAmount?: number | string | null;
  fine?: number | string | null;
  am_time_in?: string | null;
  am_time_out?: string | null;
  pm_time_in?: string | null;
  pm_time_out?: string | null;
  amTimeIn?: string | null;
  amTimeOut?: string | null;
  pmTimeIn?: string | null;
  pmTimeOut?: string | null;
  am_grace_in?: number | string | null;
  am_grace_out?: number | string | null;
  pm_grace_in?: number | string | null;
  pm_grace_out?: number | string | null;
  year_level?: string | number | null;
  course_code?: string | null;
  major?: string | null;
  department_name?: string | null;
  department?: string | null;
  is_mandatory?: boolean | number | string;
  is_all_departments?: boolean | number | string;
  requires_password?: boolean;
  requiresPassword?: boolean;
  has_attendance_password?: boolean;
  hasAttendancePassword?: boolean;
  created_by?: string | null;
  created_by_username?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  source?: string;
  reg?: number;
  att_rate?: number | null;
  attRate?: number | null;
  time_slots?: string;
  timeSlots?: string;
};

export type DisplayEvent = {
  id: string | number | null;
  name: string;
  icon: string;
  date: string;
  duration: string;
  venue: string;
  timeSlots: string;
  year_level: string | null;
  course_code: string | null;
  major: string | null;
  department_name: string | null;
  am_grace_in: number | null;
  am_grace_out: number | null;
  pm_grace_in: number | null;
  pm_grace_out: number | null;
  amGraceInMinutes: number | null;
  amGraceOutMinutes: number | null;
  pmGraceInMinutes: number | null;
  pmGraceOutMinutes: number | null;
  am_time_in: string | null;
  am_time_out: string | null;
  pm_time_in: string | null;
  pm_time_out: string | null;
  amTimeInDisplay: string | null;
  amTimeOutDisplay: string | null;
  pmTimeInDisplay: string | null;
  pmTimeOutDisplay: string | null;
  reg: number;
  attRate: number | null;
  fine: number | string | null;
  status: string;
  audience_notes: string | null;
  is_mandatory: boolean;
  is_all_departments: boolean;
  created_by: string | null;
  created_by_username: string | null;
  created_at: string | null;
  updated_at: string | null;
  audiences: unknown;
  source: string;
  requiresPassword: boolean;
};

export type CurrentEventBundle = {
  current: DisplayEvent | null;
  upcoming: DisplayEvent[];
  ongoing: DisplayEvent[];
};

export type AddEventPayload = Record<string, unknown>;
