import { useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import axiosApi from "../api/axiosInstance";
import SidebarNavIcon from "./SidebarNavIcon";
import SidebarBrand from "./SidebarBrand";
import SidebarUserFullName from "./SidebarUserFullName";
import UserCircleIcon from "./UserCircleIcon";
import NavbarAcademicPeriod from "./NavbarAcademicPeriod";
import { getAppNavItems } from "../utils/appNav";
import { isCsgPresident } from "../utils/roles";
import { useGovernorScope } from "../hooks/useGovernorScope";
import {
  useExportSecuritySettings,
  useSetExportPassword,
  useToggleExportProtection,
  useVerifyExportFile,
  extractFingerprintFromCsv,
  getApiErrorMessage,
} from "../hooks/useExportSecurity";
import type { DeskPageProps } from "../types/desk-pages";

type AuditLogEntry = {
  id: number;
  action: "export" | "import" | "import_rejected";
  event_id: number | null;
  event_name: string | null;
  username: string;
  file_name: string | null;
  protected: number;
  import_status: string | null;
  notes: string | null;
  created_at: string;
};

function StatusBadge({ enabled }: { enabled: boolean }) {
  return enabled ? (
    <span className="inline-flex items-center gap-1.5 rounded-full bg-green-100 px-2.5 py-0.5 text-xs font-semibold text-green-800 ring-1 ring-green-200">
      <span className="h-1.5 w-1.5 rounded-full bg-green-500" />
      Protection Enabled
    </span>
  ) : (
    <span className="inline-flex items-center gap-1.5 rounded-full bg-gray-100 px-2.5 py-0.5 text-xs font-semibold text-gray-600 ring-1 ring-gray-200">
      <span className="h-1.5 w-1.5 rounded-full bg-gray-400" />
      Protection Disabled
    </span>
  );
}

function formatDate(ts: string | null | undefined) {
  if (!ts) return "—";
  const d = new Date(ts);
  return Number.isNaN(d.getTime()) ? ts : d.toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" });
}

export default function ExportSecurityPage({ onNavigate, onLogout }: DeskPageProps) {
  const { role } = useGovernorScope();
  const isCsg = isCsgPresident(role);

  const { data: settings, isLoading } = useExportSecuritySettings(isCsg);

  const { data: auditLogData, refetch: refetchAudit } = useQuery<{ log: AuditLogEntry[] }>({
    queryKey: ["export-audit-log"],
    enabled: isCsg,
    queryFn: async () => {
      const res = await axiosApi.get("/export/audit-log?limit=30");
      return res.data as { log: AuditLogEntry[] };
    },
    staleTime: 15_000,
  });
  const auditLog = auditLogData?.log ?? [];
  const setPasswordMutation = useSetExportPassword();
  const toggleMutation = useToggleExportProtection();
  const verifyMutation = useVerifyExportFile();

  const [showLogout, setShowLogout] = useState(false);
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [formSuccess, setFormSuccess] = useState("");
  const [formError, setFormError] = useState("");
  const [verifyResult, setVerifyResult] = useState<{ valid: boolean; message: string } | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const navItems = getAppNavItems({ isCsgPresident: isCsg });

  const handleSetPassword = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormSuccess("");
    setFormError("");
    if (password.length < 4) { setFormError("Password must be at least 4 characters."); return; }
    if (password !== confirmPassword) { setFormError("Passwords do not match."); return; }

    setPasswordMutation.mutate(password, {
      onSuccess: (data) => {
        setFormSuccess(data.message || "Export password saved successfully.");
        setPassword("");
        setConfirmPassword("");
      },
      onError: (err) => setFormError(getApiErrorMessage(err, "Failed to save password.")),
    });
  };

  const handleToggle = (enable: boolean) => {
    setFormSuccess("");
    setFormError("");
    toggleMutation.mutate(enable, {
      onSuccess: (data) => setFormSuccess(data.message || `Protection ${enable ? "enabled" : "disabled"}.`),
      onError: (err) => setFormError(getApiErrorMessage(err, "Failed to update protection status.")),
    });
  };

  const processVerifyFile = (file: File) => {
    setVerifyResult(null);
    const reader = new FileReader();
    reader.onload = (e) => {
      const text = String(e.target?.result ?? "");
      const fingerprint = extractFingerprintFromCsv(text);
      if (!fingerprint) {
        setVerifyResult({
          valid: false,
          message: "No export signature found in this file. It was not generated by the NMCI system or does not have password protection.",
        });
        return;
      }
      verifyMutation.mutate(fingerprint, {
        onSuccess: (result) => setVerifyResult(result),
        onError: (err) => setVerifyResult({ valid: false, message: getApiErrorMessage(err, "Verification failed.") }),
      });
    };
    reader.readAsText(file);
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) processVerifyFile(file);
    e.target.value = "";
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files?.[0];
    if (file) processVerifyFile(file);
  };

  return (
    <div className="flex min-h-screen bg-gray-50 [&_button]:cursor-pointer">
      {/* Sidebar */}
      <aside className="sticky top-0 h-screen max-h-screen w-64 shrink-0 self-start overflow-y-auto bg-[#07713C] text-white flex flex-col">
        <SidebarBrand />
        <nav className="flex-1 px-4 space-y-1 pb-4">
          {navItems.map((item) => (
            <button
              key={item.id}
              type="button"
              onClick={() => onNavigate?.(item.id)}
              className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg text-left text-sm font-medium transition-colors ${
                item.id === "export_security" ? "bg-[#055a2e] text-white" : "text-green-100 hover:bg-white/15"
              }`}
            >
              <SidebarNavIcon navId={item.id} />
              {item.label}
            </button>
          ))}
        </nav>
        <SidebarUserFullName />
      </aside>

      {/* Main */}
      <div className="flex-1 flex flex-col min-w-0">
        <header className="border-b border-[#07713c]/30 bg-white px-6 py-4">
          <div className="mx-auto flex w-full max-w-7xl items-center justify-between gap-3">
            <div>
              <h1 className="font-[Inter,sans-serif] text-[30px] font-extrabold leading-tight text-[#07713c]">
                Export Security Settings
              </h1>
              <NavbarAcademicPeriod className="mt-1" />
            </div>
            <div className="relative">
              <button
                type="button"
                onClick={() => setShowLogout((p) => !p)}
                className="inline-flex h-11 w-11 items-center justify-center text-[#07713c] rounded-lg hover:bg-green-50"
                aria-label="Account menu"
              >
                <UserCircleIcon />
              </button>
              {showLogout && (
                <div className="absolute right-0 top-full mt-1 py-1 bg-white rounded-lg shadow-lg border border-gray-200 min-w-[120px] z-10">
                  <button
                    type="button"
                    onClick={() => { setShowLogout(false); onLogout?.(); }}
                    className="block w-full px-4 py-2 text-left text-sm text-red-600 hover:bg-red-50"
                  >
                    Logout
                  </button>
                </div>
              )}
            </div>
          </div>
        </header>

        <main className="flex-1 overflow-auto p-6 bg-[#f6f8f9]">
          <div className="mx-auto w-full max-w-4xl space-y-5">

            {/* Info banner */}
            <div className="rounded-xl border border-blue-200 bg-blue-50 px-5 py-4 flex items-start gap-3">
              <svg className="mt-0.5 h-5 w-5 shrink-0 text-blue-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.75}>
                <circle cx="12" cy="12" r="10" /><line x1="12" y1="8" x2="12" y2="12" /><line x1="12" y1="16" x2="12.01" y2="16" />
              </svg>
              <div className="text-sm text-blue-800">
                <p className="font-semibold">How Export Password Protection Works</p>
                <ul className="mt-1 space-y-0.5 text-xs list-disc list-inside text-blue-700">
                  <li>Set a System Export Password below — only you can create or change it.</li>
                  <li>When protection is <strong>enabled</strong>, all exported PDF files are automatically encrypted with this password.</li>
                  <li>Exported CSV files are signed with a unique fingerprint — no password required to open them.</li>
                  <li>Department users simply click <strong>Export → Download Protected File</strong> with no password prompt.</li>
                  <li>Use the <strong>Verify Export File</strong> section to confirm any exported CSV came from this system.</li>
                </ul>
              </div>
            </div>

            {/* Current status card */}
            {isLoading ? (
              <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm text-sm text-[#36454F]/60">Loading settings...</div>
            ) : (
              <div className="rounded-xl border border-[#07713c]/25 bg-white p-5 shadow-sm">
                <div className="flex items-center justify-between flex-wrap gap-3">
                  <div>
                    <h2 className="text-base font-bold text-[#36454F]">Current Status</h2>
                    <div className="mt-2 flex items-center gap-3 flex-wrap">
                      <StatusBadge enabled={Boolean(settings?.is_enabled)} />
                      {settings?.has_password ? (
                        <span className="text-xs text-[#36454F]/60">Password configured · Last updated {formatDate(settings?.updated_at)}</span>
                      ) : (
                        <span className="text-xs text-[#36454F]/60">No password set yet</span>
                      )}
                    </div>
                    {settings?.export_fingerprint && (
                      <p className="mt-2 text-[11px] font-mono text-[#36454F]/40 break-all">
                        Fingerprint: {settings.export_fingerprint}
                      </p>
                    )}
                  </div>
                  {settings?.has_password && (
                    <div className="flex gap-2">
                      {settings.is_enabled ? (
                        <button
                          type="button"
                          onClick={() => handleToggle(false)}
                          disabled={toggleMutation.isPending}
                          className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-[#36454F] hover:bg-gray-50 disabled:opacity-60"
                        >
                          Disable Protection
                        </button>
                      ) : (
                        <button
                          type="button"
                          onClick={() => handleToggle(true)}
                          disabled={toggleMutation.isPending}
                          className="rounded-lg border border-[#07713c] bg-[#07713c] px-4 py-2 text-sm font-semibold text-white hover:bg-[#055a2e] disabled:opacity-60"
                        >
                          Enable Protection
                        </button>
                      )}
                    </div>
                  )}
                </div>
                {formSuccess && (
                  <div className="mt-3 rounded-lg border border-green-200 bg-green-50 px-4 py-2 text-sm text-green-700">{formSuccess}</div>
                )}
                {formError && (
                  <div className="mt-3 rounded-lg border border-red-200 bg-red-50 px-4 py-2 text-sm text-red-700">{formError}</div>
                )}
              </div>
            )}

            <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
              {/* Set / Change password form */}
              <div className="rounded-xl border border-[#07713c]/25 bg-white p-5 shadow-sm">
                <h2 className="text-base font-bold text-[#36454F] mb-1">
                  {settings?.has_password ? "Change Export Password" : "Create Export Password"}
                </h2>
                <p className="text-xs text-[#36454F]/60 mb-4">
                  {settings?.has_password
                    ? "Changing the password will invalidate all previously exported PDF files."
                    : "Set a password to enable automatic protection on exported event files."}
                </p>
                <form onSubmit={handleSetPassword} className="space-y-4">
                  <div>
                    <label className="block text-xs font-medium text-[#36454F]/70 mb-1">New Export Password</label>
                    <div className="relative">
                      <input
                        type={showPassword ? "text" : "password"}
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        placeholder="Enter password (min. 4 characters)"
                        className="w-full rounded-lg border border-[#07713c]/40 bg-white px-3 py-2.5 pr-16 text-sm focus:border-[#07713c] focus:outline-none focus:ring-1 focus:ring-[#07713c]/30"
                      />
                      <button
                        type="button"
                        onClick={() => setShowPassword((p) => !p)}
                        className="absolute inset-y-0 right-3 text-xs text-[#07713c] hover:text-[#055a2e]"
                      >
                        {showPassword ? "Hide" : "Show"}
                      </button>
                    </div>
                    {password && password.length < 4 && (
                      <p className="mt-1 text-[11px] text-red-600">Minimum 4 characters required.</p>
                    )}
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-[#36454F]/70 mb-1">Confirm Password</label>
                    <input
                      type={showPassword ? "text" : "password"}
                      value={confirmPassword}
                      onChange={(e) => setConfirmPassword(e.target.value)}
                      placeholder="Confirm password"
                      className={`w-full rounded-lg border bg-white px-3 py-2.5 text-sm focus:outline-none focus:ring-1 ${
                        confirmPassword && password !== confirmPassword
                          ? "border-red-400 focus:ring-red-300"
                          : "border-[#07713c]/40 focus:border-[#07713c] focus:ring-[#07713c]/30"
                      }`}
                    />
                    {confirmPassword && password !== confirmPassword && (
                      <p className="mt-1 text-[11px] text-red-600">Passwords do not match.</p>
                    )}
                  </div>
                  <button
                    type="submit"
                    disabled={setPasswordMutation.isPending || !password || !confirmPassword || password !== confirmPassword || password.length < 4}
                    className="w-full rounded-lg bg-[#07713c] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#055a2e] disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {setPasswordMutation.isPending ? "Saving..." : settings?.has_password ? "Update Password" : "Set Password & Enable"}
                  </button>
                </form>
              </div>

              {/* Verify export file */}
              <div className="rounded-xl border border-[#07713c]/25 bg-white p-5 shadow-sm">
                <h2 className="text-base font-bold text-[#36454F] mb-1">Verify Export File</h2>
                <p className="text-xs text-[#36454F]/60 mb-4">
                  Upload an exported CSV to verify it was generated by this system using the current System Export Password.
                </p>

                <div
                  onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
                  onDragLeave={() => setIsDragging(false)}
                  onDrop={handleDrop}
                  onClick={() => fileInputRef.current?.click()}
                  className={`flex flex-col items-center justify-center rounded-xl border-2 border-dashed px-5 py-8 text-center cursor-pointer transition-colors ${
                    isDragging ? "border-[#07713c] bg-green-50" : "border-gray-300 bg-gray-50 hover:border-[#07713c]/60 hover:bg-green-50/40"
                  }`}
                >
                  <svg className="h-10 w-10 text-[#07713c]/50 mb-2" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5}>
                    <path d="M12 2L2 7l10 5 10-5-10-5z" /><path d="M2 17l10 5 10-5" /><path d="M2 12l10 5 10-5" />
                  </svg>
                  <p className="text-sm font-medium text-[#36454F]">
                    {verifyMutation.isPending ? "Verifying..." : "Drop a CSV file here or click to browse"}
                  </p>
                  <p className="text-xs text-[#36454F]/55 mt-1">Accepts exported event attendance CSV files</p>
                  <input ref={fileInputRef} type="file" accept=".csv,text/csv" className="hidden" onChange={handleFileSelect} />
                </div>

                {verifyResult && (
                  <div className={`mt-4 rounded-xl border px-4 py-3 ${
                    verifyResult.valid
                      ? "border-green-200 bg-green-50"
                      : "border-red-200 bg-red-50"
                  }`}>
                    <div className="flex items-start gap-2">
                      {verifyResult.valid ? (
                        <svg className="h-5 w-5 shrink-0 text-green-600 mt-0.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                          <path d="M20 6L9 17l-5-5" />
                        </svg>
                      ) : (
                        <svg className="h-5 w-5 shrink-0 text-red-500 mt-0.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                          <circle cx="12" cy="12" r="10" /><line x1="15" y1="9" x2="9" y2="15" /><line x1="9" y1="9" x2="15" y2="15" />
                        </svg>
                      )}
                      <p className={`text-sm font-medium ${verifyResult.valid ? "text-green-800" : "text-red-700"}`}>
                        {verifyResult.message}
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Export / Import Audit Log */}
            <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
              <div className="flex items-center justify-between mb-3">
                <h2 className="text-sm font-bold text-[#36454F]">Export & Import Audit Log</h2>
                <button
                  type="button"
                  onClick={() => void refetchAudit()}
                  className="text-xs text-[#07713c] underline hover:text-[#055a2e]"
                >
                  Refresh
                </button>
              </div>
              {auditLog.length === 0 ? (
                <p className="text-xs text-[#36454F]/50">No export or import activity recorded yet.</p>
              ) : (
                <div className="overflow-x-auto">
                  <table className="w-full text-xs">
                    <thead>
                      <tr className="border-b border-gray-100">
                        <th className="text-left py-2 pr-3 font-semibold text-[#36454F]/60">Action</th>
                        <th className="text-left py-2 pr-3 font-semibold text-[#36454F]/60">Event</th>
                        <th className="text-left py-2 pr-3 font-semibold text-[#36454F]/60">By</th>
                        <th className="text-left py-2 pr-3 font-semibold text-[#36454F]/60">Protected</th>
                        <th className="text-left py-2 pr-3 font-semibold text-[#36454F]/60">Status</th>
                        <th className="text-left py-2 font-semibold text-[#36454F]/60">Date</th>
                      </tr>
                    </thead>
                    <tbody>
                      {auditLog.map((entry) => (
                        <tr key={entry.id} className="border-b border-gray-50 hover:bg-gray-50">
                          <td className="py-1.5 pr-3">
                            <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-semibold ${
                              entry.action === "export" ? "bg-blue-100 text-blue-800"
                              : entry.action === "import" ? "bg-green-100 text-green-800"
                              : "bg-red-100 text-red-700"
                            }`}>
                              {entry.action === "import_rejected" ? "REJECTED" : entry.action.toUpperCase()}
                            </span>
                          </td>
                          <td className="py-1.5 pr-3 max-w-[160px] truncate text-[#36454F]">{entry.event_name ?? entry.file_name ?? "—"}</td>
                          <td className="py-1.5 pr-3 text-[#36454F]/70">{entry.username}</td>
                          <td className="py-1.5 pr-3">
                            {entry.protected ? (
                              <svg className="h-3.5 w-3.5 text-[#07713c]" viewBox="0 0 24 24" fill="currentColor"><path d="M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4z" /></svg>
                            ) : (
                              <span className="text-[#36454F]/30">—</span>
                            )}
                          </td>
                          <td className="py-1.5 pr-3 text-[#36454F]/60">{entry.import_status ?? "—"}</td>
                          <td className="py-1.5 text-[#36454F]/50 whitespace-nowrap">{formatDate(entry.created_at)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>

            {/* Security notes */}
            <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
              <h2 className="text-sm font-bold text-[#36454F] mb-3">Security Notes</h2>
              <ul className="space-y-2 text-xs text-[#36454F]/70">
                {[
                  "The System Export Password is stored securely using AES-256 encryption on the server.",
                  "PDF exports are password-protected using the system password — recipients must know the password to open the PDF.",
                  "CSV exports are signed with a cryptographic fingerprint — they can be opened without a password but can be verified for authenticity.",
                  "Changing the password immediately invalidates the fingerprint of all previously exported CSVs.",
                  "Only the CSG President can create, change, or reset the System Export Password.",
                  "Department users only click Export — the password protection is applied automatically with no prompt.",
                ].map((note) => (
                  <li key={note} className="flex items-start gap-2">
                    <svg className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#07713c]" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    {note}
                  </li>
                ))}
              </ul>
            </div>

          </div>
        </main>
      </div>
    </div>
  );
}
